# Generated by Django 4.0 on 2022-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdId',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
