# Generated by Django 4.0 on 2022-03-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('librarians', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueId', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('title', models.CharField(default='Book reception info', max_length=100)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('book', models.ManyToManyField(blank=True, null=True, to='books.Book')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarians.librarian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name_plural': 'bookissues',
            },
        ),
    ]
