# Generated by Django 4.0 on 2022-03-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='book',
            new_name='books',
        ),
    ]
