# Generated by Django 4.0 on 2022-03-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='issueId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
