# Generated by Django 4.0 on 2022-03-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('book_issues', '0002_rename_book_bookissue_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
